CREATE TABLE "ADMIN_ACTION_LOGS" (
    "ID" NUMBER(19) NOT NULL,
    "ADMIN_ID" NUMBER(19) NOT NULL,
    "ACTION_TYPE" VARCHAR2(30) NOT NULL,
    "TARGET_TYPE" VARCHAR2(30) NOT NULL,
    "TARGET_ID" NUMBER(19) NOT NULL,
    "DETAIL" VARCHAR2(500),
    "CREATED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "ADMIN_ACTION_LOGS"
ADD CONSTRAINT "PK_ADMIN_ACTION_LOGS" PRIMARY KEY ("ID");

ALTER TABLE "ADMIN_ACTION_LOGS"
ADD CONSTRAINT "FK_AAL_ADMIN" FOREIGN KEY ("ADMIN_ID") REFERENCES "USERS" ("ID");

CREATE SEQUENCE "ADMIN_ACTION_LOGS_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;