ALTER TABLE "ACCOUNTS" ADD "IS_ACTIVE" NUMBER(1) DEFAULT 1 NOT NULL;

CREATE TABLE "COMPETITION_ALLOWED_STOCKS" (
    "ID" NUMBER(19) NOT NULL,
    "COMPETITION_ID" NUMBER(19) NOT NULL,
    "STOCK_ID" NUMBER(19) NOT NULL
);

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "PK_COMP_ALLOWED_STOCKS" PRIMARY KEY ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "FK_CAS_COMPETITION" FOREIGN KEY ("COMPETITION_ID") REFERENCES "COMPETITIONS" ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "FK_CAS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

CREATE SEQUENCE "COMPETITION_ALLOWED_STOCKS_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;

ALTER TABLE "COMPETITIONS" ADD "MAX_PARTICIPANTS" NUMBER(10);