CREATE TABLE "ZERORISK"."POST_IMAGES" (
    "ID" NUMBER(19) NOT NULL,
    "POST_ID" NUMBER(19) NOT NULL,
    "IMAGE_URL" VARCHAR2(500) NOT NULL,
    "DISPLAY_ORDER" NUMBER(3) DEFAULT 0 NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE "ZERORISK"."POST_IMAGES"
ADD CONSTRAINT "PK_POST_IMAGES" PRIMARY KEY ("ID");

ALTER TABLE "ZERORISK"."POST_IMAGES"
ADD CONSTRAINT "FK_POST_IMAGES_POST" FOREIGN KEY ("POST_ID") REFERENCES "ZERORISK"."POSTS" ("ID");

CREATE SEQUENCE "ZERORISK"."POST_IMAGES_SEQ"
START WITH 1 INCREMENT BY 50;

CREATE TABLE "ZERORISK"."CHAT_MESSAGE_IMAGES" (
    "ID" NUMBER(19) NOT NULL,
    "CHAT_MESSAGE_ID" NUMBER(19) NOT NULL,
    "IMAGE_URL" VARCHAR2(500) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE "ZERORISK"."CHAT_MESSAGE_IMAGES"
ADD CONSTRAINT "PK_CHAT_MESSAGE_IMAGES" PRIMARY KEY ("ID");

ALTER TABLE "ZERORISK"."CHAT_MESSAGE_IMAGES"
ADD CONSTRAINT "FK_CHAT_MSG_IMAGES_MSG" FOREIGN KEY ("CHAT_MESSAGE_ID") REFERENCES "ZERORISK"."CHAT_MESSAGES" ("ID");

CREATE SEQUENCE "ZERORISK"."CHAT_MESSAGE_IMAGES_SEQ"
START WITH 1 INCREMENT BY 50;

ALTER TABLE "ZERORISK"."POSTS" DROP COLUMN "IS_PROFIT_CERT";

ALTER TABLE "ZERORISK"."POSTS" DROP COLUMN "CERT_IMAGE_URL";