CREATE TABLE "ADMIN_ACTION_LOGS" (
    "ID" NUMBER(19) NOT NULL,
    "ADMIN_ID" NUMBER(19) NOT NULL,
    "ACTION_TYPE" VARCHAR2(30) NOT NULL,
    "TARGET_TYPE" VARCHAR2(30) NOT NULL,
    "TARGET_ID" NUMBER(19) NOT NULL,
    "DETAIL" VARCHAR2(500),
    "CREATED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "ADMIN_ACTION_LOGS"
ADD CONSTRAINT "PK_ADMIN_ACTION_LOGS" PRIMARY KEY ("ID");

ALTER TABLE "ADMIN_ACTION_LOGS"
ADD CONSTRAINT "FK_AAL_ADMIN" FOREIGN KEY ("ADMIN_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "ADMIN_ACTION_LOGS" ADD "IP_ADDRESS" VARCHAR2(45);

CREATE SEQUENCE "ADMIN_ACTION_LOGS_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;

UPDATE ACCOUNTS SET IS_ACTIVE = 1 WHERE IS_ACTIVE IS NULL;

COMMIT;

ALTER TABLE ACCOUNTS MODIFY (IS_ACTIVE NOT NULL);

ALTER TABLE "ACCOUNTS" ADD "IS_ACTIVE" NUMBER(1) DEFAULT 1 NOT NULL;

CREATE TABLE "COMPETITION_ALLOWED_STOCKS" (
    "ID" NUMBER(19) NOT NULL,
    "COMPETITION_ID" NUMBER(19) NOT NULL,
    "STOCK_ID" NUMBER(19) NOT NULL
);

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "PK_COMP_ALLOWED_STOCKS" PRIMARY KEY ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "FK_CAS_COMPETITION" FOREIGN KEY ("COMPETITION_ID") REFERENCES "COMPETITIONS" ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "FK_CAS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

CREATE SEQUENCE "COMPETITION_ALLOWED_STOCKS_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;

ALTER TABLE "COMPETITIONS" ADD "MAX_PARTICIPANTS" NUMBER(10);

ALTER TABLE "FOLLOWS"
ADD CONSTRAINT "UK_FOLLOWS_PAIR" UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID");

CREATE TABLE "ZERORISK"."POST_IMAGES" (
    "ID" NUMBER(19) NOT NULL,
    "POST_ID" NUMBER(19) NOT NULL,
    "IMAGE_URL" VARCHAR2(500) NOT NULL,
    "DISPLAY_ORDER" NUMBER(3) DEFAULT 0 NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE "ZERORISK"."POST_IMAGES"
ADD CONSTRAINT "PK_POST_IMAGES" PRIMARY KEY ("ID");

ALTER TABLE "ZERORISK"."POST_IMAGES"
ADD CONSTRAINT "FK_POST_IMAGES_POST" FOREIGN KEY ("POST_ID") REFERENCES "ZERORISK"."POSTS" ("ID");

CREATE SEQUENCE "ZERORISK"."POST_IMAGES_SEQ"
START WITH 1 INCREMENT BY 50;

CREATE TABLE "ZERORISK"."CHAT_MESSAGE_IMAGES" (
    "ID" NUMBER(19) NOT NULL,
    "CHAT_MESSAGE_ID" NUMBER(19) NOT NULL,
    "IMAGE_URL" VARCHAR2(500) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE "ZERORISK"."CHAT_MESSAGE_IMAGES"
ADD CONSTRAINT "PK_CHAT_MESSAGE_IMAGES" PRIMARY KEY ("ID");

ALTER TABLE "ZERORISK"."CHAT_MESSAGE_IMAGES"
ADD CONSTRAINT "FK_CHAT_MSG_IMAGES_MSG" FOREIGN KEY ("CHAT_MESSAGE_ID") REFERENCES "ZERORISK"."CHAT_MESSAGES" ("ID");

CREATE SEQUENCE "ZERORISK"."CHAT_MESSAGE_IMAGES_SEQ"
START WITH 1 INCREMENT BY 50;

ALTER TABLE "ZERORISK"."POSTS" DROP COLUMN "IS_PROFIT_CERT";

ALTER TABLE "ZERORISK"."POSTS" DROP COLUMN "CERT_IMAGE_URL";

DROP TABLE MONTHLY_CHARGE_SETTINGS PURGE;

DROP SEQUENCE MONTHLY_CHARGE_SETTINGS_SEQ;

CREATE TABLE "ANNOUNCEMENTS" (
    "ID" NUMBER(19) NOT NULL,
    "TAG" VARCHAR2(20) NOT NULL,
    "TITLE" VARCHAR2(200) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "IS_IMPORTANT" NUMBER(1) DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER(19) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "ANNOUNCEMENTS"
ADD CONSTRAINT "PK_ANNOUNCEMENTS" PRIMARY KEY ("ID");

CREATE SEQUENCE "ANNOUNCEMENTS_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE TABLE "SYSTEM_NOTICES" (
    "ID" NUMBER(19) NOT NULL,
    "SEVERITY" VARCHAR2(20) NOT NULL,
    "TITLE" VARCHAR2(200) NOT NULL,
    "MESSAGE" VARCHAR2(1000) NOT NULL,
    "IS_ACTIVE" NUMBER(1) DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER(19) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "SYSTEM_NOTICES"
ADD CONSTRAINT "PK_SYSTEM_NOTICES" PRIMARY KEY ("ID");

CREATE SEQUENCE "SYSTEM_NOTICES_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;

ALTER TABLE "USERS" ADD "OAUTH_PROVIDER_ID" VARCHAR2(50);

ALTER TABLE "OPENBANKING_AUTHS" ADD "FINTECH_USE_NUM" VARCHAR2(24);

ALTER TABLE "USERS"
ADD "HAS_CLAIMED_PRACTICE_CREDIT" NUMBER(1) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN "USERS"."HAS_CLAIMED_PRACTICE_CREDIT" IS '연습용 크레딧(100만원) 수령 여부. 1=수령함 0=미수령';

ALTER TABLE "COMPETITIONS" ADD "RECRUIT_START_AT" TIMESTAMP;

ALTER TABLE "POSTS"
ADD "DISLIKE_COUNT" NUMBER(10) DEFAULT 0 NOT NULL;

UPDATE PROFILE_SETTINGS
SET
    SHOW_PORTFOLIO = 0,
    SHOW_TRADES = 0
WHERE
    SHOW_PORTFOLIO = 1
    AND SHOW_TRADES = 1;

ALTER TABLE "USERS" ADD CONSTRAINT "UK_USERS_EMAIL" UNIQUE ("EMAIL");

ALTER TABLE "USERS"
ADD CONSTRAINT "UK_USERS_NICKNAME" UNIQUE ("NICKNAME");