CREATE TABLE "ANNOUNCEMENTS" (
    "ID" NUMBER(19) NOT NULL,
    "TAG" VARCHAR2(20) NOT NULL,
    "TITLE" VARCHAR2(200) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "IS_IMPORTANT" NUMBER(1) DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER(19) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "ANNOUNCEMENTS"
ADD CONSTRAINT "PK_ANNOUNCEMENTS" PRIMARY KEY ("ID");

CREATE SEQUENCE "ANNOUNCEMENTS_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE TABLE "SYSTEM_NOTICES" (
    "ID" NUMBER(19) NOT NULL,
    "SEVERITY" VARCHAR2(20) NOT NULL,
    "TITLE" VARCHAR2(200) NOT NULL,
    "MESSAGE" VARCHAR2(1000) NOT NULL,
    "IS_ACTIVE" NUMBER(1) DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER(19) NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL
);

ALTER TABLE "SYSTEM_NOTICES"
ADD CONSTRAINT "PK_SYSTEM_NOTICES" PRIMARY KEY ("ID");

CREATE SEQUENCE "SYSTEM_NOTICES_SEQ"
START WITH 1 INCREMENT BY 50 NOCACHE;