ALTER TABLE "COMPETITIONS" ADD "RECRUIT_START_AT" TIMESTAMP;

ALTER TABLE "POSTS"
ADD "DISLIKE_COUNT" NUMBER(10) DEFAULT 0 NOT NULL;

UPDATE PROFILE_SETTINGS
SET
    SHOW_PORTFOLIO = 0,
    SHOW_TRADES = 0
WHERE
    SHOW_PORTFOLIO = 1
    AND SHOW_TRADES = 1;