-- ============================================================
-- ZeroRisk DDL v2 (Oracle XE)
-- 변경사항 (v1 -> v2):
--   1. USERS.LEVEL -> USERS.USER_LEVEL (예약어 회피)
--   2. USERS.ROLE  -> USERS.USER_ROLE  (예약어 회피)
--   3. 전 테이블 SEQUENCE 추가 (allocationSize=50 매칭)
--   4. FK 제약조건 추가
-- ============================================================

-- ============================================================
-- 1. TABLE 생성
-- ============================================================

CREATE TABLE "USERS" (
    "ID" NUMBER (19) NOT NULL,
    "EMAIL" VARCHAR2 (100) NOT NULL,
    "NICKNAME" VARCHAR2 (12) NOT NULL,
    "PASSWORD" VARCHAR2 (255) NULL,
    "USER_ROLE" VARCHAR2 (10) DEFAULT 'USER' NOT NULL,
    "STATUS" VARCHAR2 (10) DEFAULT 'ACTIVE' NOT NULL,
    "OAUTH_PROVIDER" VARCHAR2 (20) NULL,
    "PROFILE_IMAGE_URL" CLOB NULL,
    "ACTIVITY_SCORE" NUMBER (10) DEFAULT 0 NOT NULL,
    "USER_LEVEL" NUMBER (5) DEFAULT 1 NOT NULL,
    "SUSPENDED_UNTIL" TIMESTAMP NULL,
    "SUSPENSION_REASON" CLOB NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "OAUTH_PROVIDER_ID" VARCHAR2 (50) NULL,
    "HAS_CLAIMED_PRACTICE_CREDIT" NUMBER (1) DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN "USERS"."EMAIL" IS '로그인 이메일';

COMMENT ON COLUMN "USERS"."NICKNAME" IS '닉네임 최대 12자';

COMMENT ON COLUMN "USERS"."PASSWORD" IS 'BCrypt 암호화. 소셜 로그인 시 NULL';

COMMENT ON COLUMN "USERS"."USER_ROLE" IS 'USER | ADMIN (원래 ROLE, Oracle 예약어 회피)';

COMMENT ON COLUMN "USERS"."STATUS" IS 'ACTIVE | SUSPENDED | QUIT';

COMMENT ON COLUMN "USERS"."OAUTH_PROVIDER" IS 'google | kakao';

COMMENT ON COLUMN "USERS"."ACTIVITY_SCORE" IS '게시글x5 + 댓글x2 + 추천x10';

COMMENT ON COLUMN "USERS"."USER_LEVEL" IS '원래 LEVEL, Oracle 예약어(계층쿼리) 회피';

COMMENT ON COLUMN "USERS"."SUSPENDED_UNTIL" IS '정지 해제 시각. NULL = 영구 정지';

COMMENT ON COLUMN "USERS"."HAS_CLAIMED_PRACTICE_CREDIT" IS '연습용 크레딧(100만원) 수령 여부. 1=수령함 0=미수령';

CREATE TABLE "STOCKS" (
    "ID" NUMBER (19) NOT NULL,
    "CODE" VARCHAR2 (6) NOT NULL,
    "STANDARD_CODE" VARCHAR2 (12) NULL,
    "NAME" VARCHAR2 (100) NOT NULL,
    "MARKET" VARCHAR2 (10) NOT NULL,
    "ACTIVE" NUMBER (1) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "STOCKS"."STANDARD_CODE" IS '표준코드 (KIS API)';

COMMENT ON COLUMN "STOCKS"."MARKET" IS 'KOSPI | KOSDAQ';

COMMENT ON COLUMN "STOCKS"."ACTIVE" IS '상장 활성 여부. 상장폐지 시 0';

CREATE TABLE "COMPETITIONS" (
    "ID" NUMBER (19) NOT NULL,
    "TITLE" VARCHAR2 (100) NOT NULL,
    "DESCRIPTION" CLOB NULL,
    "RECRUIT_START_AT" TIMESTAMP NULL,
    "RECRUIT_END_AT" TIMESTAMP NULL,
    "START_AT" TIMESTAMP NOT NULL,
    "END_AT" TIMESTAMP NOT NULL,
    "STATUS" VARCHAR2 (15) DEFAULT 'SCHEDULED' NOT NULL,
    "SEED_MONEY" NUMBER (19) NOT NULL,
    "IS_PUBLIC" NUMBER (1) DEFAULT 1 NOT NULL,
    "CREATED_BY" NUMBER (19) NOT NULL,
    "MAX_PARTICIPANTS" NUMBER (10) NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "COMPETITIONS"."RECRUIT_START_AT" IS '참가 모집 시작 시각. NULL이면 제한 없음';

COMMENT ON COLUMN "COMPETITIONS"."RECRUIT_END_AT" IS '참가 모집 마감 시각. NULL이면 제한 없음';

COMMENT ON COLUMN "COMPETITIONS"."SEED_MONEY" IS '대회 초기 고정 시드머니';

COMMENT ON COLUMN "COMPETITIONS"."IS_PUBLIC" IS '1=공개 0=비공개';

COMMENT ON COLUMN "COMPETITIONS"."MAX_PARTICIPANTS" IS '최대 참가자 수. NULL이면 제한 없음';

COMMENT ON COLUMN "COMPETITIONS"."STATUS" IS 'SCHEDULED | ONGOING | CALCULATING | ENDED';

CREATE TABLE "ACCOUNTS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "BALANCE" NUMBER (19) DEFAULT 0 NOT NULL,
    "INITIAL_SEED_MONEY" NUMBER (19) DEFAULT 0 NOT NULL,
    "ACCOUNT_TYPE" VARCHAR2 (15) NOT NULL,
    "COMPETITION_ID" NUMBER (19) NULL,
    "IS_ACTIVE" NUMBER (1) DEFAULT 1 NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "ACCOUNTS"."INITIAL_SEED_MONEY" IS '누적 투입 원금. 수익률 산출의 기준값이며 시드머니 충전 시 함께 증가';

COMMENT ON COLUMN "ACCOUNTS"."ACCOUNT_TYPE" IS 'BASIC | COMPETITION';

COMMENT ON COLUMN "ACCOUNTS"."COMPETITION_ID" IS '대회 계좌일 때만 값 존재';

COMMENT ON COLUMN "ACCOUNTS"."IS_ACTIVE" IS '계좌 활성 여부. 회원 탈퇴/대회 참가 취소 시 0으로 비활성화';

CREATE TABLE "WATCHLIST_GROUPS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "NAME" VARCHAR2 (50) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "WATCHLIST_GROUPS"."NAME" IS '그룹 이름 최대 50자';

CREATE TABLE "POSTS" (
    "ID" NUMBER (19) NOT NULL,
    "BOARD_TYPE" VARCHAR2 (10) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NULL,
    "TITLE" VARCHAR2 (200) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "IS_PROFIT_CERT" NUMBER (1) DEFAULT 0 NOT NULL,
    "CERT_IMAGE_URL" CLOB NULL,
    "VIEW_COUNT" NUMBER (10) DEFAULT 0 NOT NULL,
    "LIKE_COUNT" NUMBER (10) DEFAULT 0 NOT NULL,
    "DISLIKE_COUNT" NUMBER (10) DEFAULT 0 NOT NULL,
    "IS_DELETED" NUMBER (1) DEFAULT 0 NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "UPDATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "POSTS"."IS_PROFIT_CERT" IS '1=수익률 인증 카드 게시글';

COMMENT ON COLUMN "POSTS"."CERT_IMAGE_URL" IS '수익률 인증 카드 S3 URL';

COMMENT ON COLUMN "POSTS"."IS_DELETED" IS '소프트 삭제';

COMMENT ON COLUMN "POSTS"."BOARD_TYPE" IS 'FREE | STOCK | NOTICE';

CREATE TABLE "PROFILE_SETTINGS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "SHOW_RETURN_RATE" NUMBER (1) DEFAULT 1 NOT NULL,
    "SHOW_PORTFOLIO" NUMBER (1) DEFAULT 0 NOT NULL,
    "SHOW_TRADES" NUMBER (1) DEFAULT 0 NOT NULL,
    "SHOW_STATS" NUMBER (1) DEFAULT 1 NOT NULL,
    "SHOW_COMPETITIONS" NUMBER (1) DEFAULT 1 NOT NULL
);

COMMENT ON COLUMN "PROFILE_SETTINGS"."SHOW_PORTFOLIO" IS '포트폴리오 공개. 기본 비공개';

COMMENT ON COLUMN "PROFILE_SETTINGS"."SHOW_TRADES" IS '거래내역 공개. 기본 비공개';

CREATE TABLE "CHAT_MESSAGES" (
    "ID" NUMBER (19) NOT NULL,
    "CHANNEL_TYPE" VARCHAR2 (15) NOT NULL,
    "CHANNEL_ID" VARCHAR2 (50) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "MESSAGE" CLOB NOT NULL,
    "IS_DELETED" NUMBER (1) DEFAULT 0 NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "CHAT_MESSAGES"."CHANNEL_TYPE" IS 'STOCK | COMPETITION';

COMMENT ON COLUMN "CHAT_MESSAGES"."CHANNEL_ID" IS '종목코드(005930) 또는 대회ID';

CREATE TABLE "INQUIRIES" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "CATEGORY" VARCHAR2 (30) NOT NULL,
    "TITLE" VARCHAR2 (200) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "ANSWER" CLOB NULL,
    "STATUS" VARCHAR2 (15) DEFAULT 'PENDING' NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "ANSWERED_AT" TIMESTAMP NULL
);

COMMENT ON COLUMN "INQUIRIES"."STATUS" IS 'PENDING | ANSWERED';

CREATE TABLE "ORDERS" (
    "ID" NUMBER (19) NOT NULL,
    "ACCOUNT_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL,
    "SIDE" VARCHAR2 (10) NOT NULL,
    "ORDER_TYPE" VARCHAR2 (10) NOT NULL,
    "QUANTITY" NUMBER (10) NOT NULL,
    "LIMIT_PRICE" NUMBER (19) NULL,
    "STATUS" VARCHAR2 (10) DEFAULT 'PENDING' NOT NULL,
    "FILLED_PRICE" NUMBER (19) NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    "FILLED_AT" TIMESTAMP NULL
);

COMMENT ON COLUMN "ORDERS"."SIDE" IS 'BUY(매수) | SELL(매도)';

COMMENT ON COLUMN "ORDERS"."ORDER_TYPE" IS 'MARKET(시장가) | LIMIT(지정가)';

COMMENT ON COLUMN "ORDERS"."LIMIT_PRICE" IS '지정가 주문의 목표가. 주문 시점에 체결되지 않으면 PENDING으로 남아 스케줄러가 이 값으로 체결 여부를 판단(예약 주문)';

COMMENT ON COLUMN "ORDERS"."STATUS" IS 'PENDING | FILLED | CANCELLED';

COMMENT ON COLUMN "ORDERS"."FILLED_PRICE" IS '실제 체결가. 미체결 주문은 NULL';

CREATE TABLE "TRADES" (
    "ID" NUMBER (19) NOT NULL,
    "ORDER_ID" NUMBER (19) NOT NULL,
    "ACCOUNT_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL,
    "SIDE" VARCHAR2 (10) NOT NULL,
    "QUANTITY" NUMBER (10) NOT NULL,
    "PRICE" NUMBER (19) NOT NULL,
    "TRADED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "TRADES"."SIDE" IS 'BUY(매수) | SELL(매도)';

CREATE TABLE "COMMENTS" (
    "ID" NUMBER (19) NOT NULL,
    "POST_ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "PARENT_ID" NUMBER (19) NULL,
    "CONTENT" CLOB NOT NULL,
    "IS_DELETED" NUMBER (1) DEFAULT 0 NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE "PORTFOLIO_SNAPSHOTS" (
    "ID" NUMBER (19) NOT NULL,
    "ACCOUNT_ID" NUMBER (19) NOT NULL,
    "SNAPSHOT_DATE" DATE NOT NULL,
    "TOTAL_ASSET" NUMBER (19) NOT NULL,
    "CASH" NUMBER (19) NOT NULL,
    "STOCK_VALUE" NUMBER (19) NOT NULL
);

CREATE TABLE "PRIZE_HISTORY" (
    "ID" NUMBER (19) NOT NULL,
    "COMPETITION_ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "ACCOUNT_ID" NUMBER (19) NOT NULL,
    "RANK_POSITION" NUMBER (3) NOT NULL,
    "PRIZE_AMOUNT" NUMBER (19) NOT NULL,
    "PAID_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "PRIZE_HISTORY"."ACCOUNT_ID" IS '포인트가 지급된 기본 계좌 ID';

COMMENT ON COLUMN "PRIZE_HISTORY"."PRIZE_AMOUNT" IS '실제 지급된 포인트 (기본 계좌 예수금에 추가됨)';

CREATE TABLE "ALERT_SETTINGS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "ORDER_FILLED" NUMBER (1) DEFAULT 1 NOT NULL,
    "COMMENT_ADDED" NUMBER (1) DEFAULT 1 NOT NULL,
    "COMPETITION" NUMBER (1) DEFAULT 1 NOT NULL,
    "PRICE_ALERT" NUMBER (1) DEFAULT 1 NOT NULL,
    "INQUIRY_ANSWERED" NUMBER (1) DEFAULT 1 NOT NULL
);

CREATE TABLE "COMPETITION_PARTICIPANTS" (
    "ID" NUMBER (19) NOT NULL,
    "COMPETITION_ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "ACCOUNT_ID" NUMBER (19) NOT NULL,
    "TOTAL_ASSET" NUMBER (19) DEFAULT 0 NOT NULL,
    "RETURN_RATE" NUMBER (10, 4) DEFAULT 0 NOT NULL,
    "RANK_POSITION" NUMBER (10) NULL,
    "JOINED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "COMPETITION_PARTICIPANTS"."RANK_POSITION" IS 'Oracle RANK() 결과. 수익률1순위 총자산2순위';

CREATE TABLE "WATCHLIST_FAVORITES" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "GROUP_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "WATCHLIST_FAVORITES"."GROUP_ID" IS '관심종목은 반드시 그룹에 속함. 그룹 없는 관심종목은 허용하지 않음';

CREATE TABLE "NOTIFICATIONS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "TYPE" VARCHAR2 (30) NOT NULL,
    "TITLE" VARCHAR2 (200) NOT NULL,
    "MESSAGE" CLOB NOT NULL,
    "IS_READ" NUMBER (1) DEFAULT 0 NOT NULL,
    "TARGET_URL" VARCHAR2 (500) NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "NOTIFICATIONS"."TYPE" IS 'ORDER_FILLED | COMMENT_ADDED | COMPETITION | PRICE_ALERT | INQUIRY_ANSWERED';

COMMENT ON COLUMN "NOTIFICATIONS"."TARGET_URL" IS '클릭 시 이동 URL';

CREATE TABLE "POST_VOTES" (
    "ID" NUMBER (19) NOT NULL,
    "POST_ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "VOTE_TYPE" VARCHAR2 (10) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "POST_VOTES"."VOTE_TYPE" IS 'LIKE | DISLIKE';

CREATE TABLE "OPENBANKING_AUTHS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "BANK_NAME" VARCHAR2 (20) NOT NULL,
    "ACCOUNT_NUM_MASKED" VARCHAR2 (30) NOT NULL,
    "FINTECH_USE_NUM" VARCHAR2 (24) NULL,
    "VERIFIED_AT" TIMESTAMP NOT NULL,
    "TOTAL_RECEIVED_POINTS" NUMBER (19) DEFAULT 0 NOT NULL,
    "VERSION" NUMBER (10) DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN "OPENBANKING_AUTHS"."ACCOUNT_NUM_MASKED" IS '마스킹 계좌번호 (표시용)';

COMMENT ON COLUMN "OPENBANKING_AUTHS"."FINTECH_USE_NUM" IS '오픈뱅킹 핀테크이용번호 (실제 이체용 식별자)';

COMMENT ON COLUMN "OPENBANKING_AUTHS"."TOTAL_RECEIVED_POINTS" IS '누적 수령 포인트. 재충전 한도 계산용';

COMMENT ON COLUMN "OPENBANKING_AUTHS"."VERSION" IS 'JPA 낙관적 락 @Version';

CREATE TABLE "PRICE_ALERTS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL,
    "TARGET_PRICE" NUMBER (19) NOT NULL,
    "DIRECTION" VARCHAR2 (10) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "PRICE_ALERTS"."DIRECTION" IS 'ABOVE(목표가 이상 도달) | BELOW(목표가 이하 도달)';

CREATE TABLE "FOLLOWS" (
    "ID" NUMBER (19) NOT NULL,
    "FOLLOWER_ID" NUMBER (19) NOT NULL,
    "FOLLOWING_ID" NUMBER (19) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE "HOLDINGS" (
    "ID" NUMBER (19) NOT NULL,
    "ACCOUNT_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL,
    "QUANTITY" NUMBER (10) NOT NULL,
    "AVERAGE_PRICE" NUMBER (19) NOT NULL,
    "UPDATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "HOLDINGS"."AVERAGE_PRICE" IS '매수 평균 단가. 추가 매수 시 가중 평균으로 갱신';

CREATE TABLE "STOCK_ALIASES" (
    "ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL,
    "ALIAS" VARCHAR2 (50) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE "REPORTS" (
    "ID" NUMBER (19) NOT NULL,
    "TARGET_TYPE" VARCHAR2 (15) NOT NULL,
    "TARGET_ID" NUMBER (19) NOT NULL,
    "REPORTER_ID" NUMBER (19) NOT NULL,
    "REASON" VARCHAR2 (200) NOT NULL,
    "STATUS" VARCHAR2 (15) DEFAULT 'PENDING' NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "REPORTS"."STATUS" IS 'PENDING | PROCESSED | REJECTED';

COMMENT ON COLUMN "REPORTS"."TARGET_TYPE" IS 'POST | COMMENT | USER 등 - 대상에 따라 TARGET_ID가 가리키는 테이블이 달라짐 (다형성, FK 미설정)';

CREATE TABLE "ANNOUNCEMENTS" (
    "ID" NUMBER (19) NOT NULL,
    "TAG" VARCHAR2 (20) NOT NULL,
    "TITLE" VARCHAR2 (200) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "IS_IMPORTANT" NUMBER (1) DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER (19) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "ANNOUNCEMENTS"."TAG" IS 'EVENT | GUIDE | MAINTENANCE';

COMMENT ON COLUMN "ANNOUNCEMENTS"."IS_IMPORTANT" IS '1=중요 공지 (상단 고정 등)';

CREATE TABLE "SYSTEM_NOTICES" (
    "ID" NUMBER (19) NOT NULL,
    "SEVERITY" VARCHAR2 (20) NOT NULL,
    "TITLE" VARCHAR2 (200) NOT NULL,
    "MESSAGE" VARCHAR2 (1000) NOT NULL,
    "IS_ACTIVE" NUMBER (1) DEFAULT 0 NOT NULL,
    "CREATED_BY" NUMBER (19) NOT NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "SYSTEM_NOTICES"."SEVERITY" IS 'MAINTENANCE | INCIDENT | NOTICE';

COMMENT ON COLUMN "SYSTEM_NOTICES"."IS_ACTIVE" IS '긴급 알림 팝업 노출 여부';

CREATE TABLE "ADMIN_ACTION_LOGS" (
    "ID" NUMBER (19) NOT NULL,
    "ADMIN_ID" NUMBER (19) NOT NULL,
    "ACTION_TYPE" VARCHAR2 (30) NOT NULL,
    "TARGET_TYPE" VARCHAR2 (30) NOT NULL,
    "TARGET_ID" NUMBER (19) NOT NULL,
    "DETAIL" VARCHAR2 (500) NULL,
    "IP_ADDRESS" VARCHAR2 (45) NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON COLUMN "ADMIN_ACTION_LOGS"."ADMIN_ID" IS '행위를 수행한 관리자 USER_ID';

COMMENT ON COLUMN "ADMIN_ACTION_LOGS"."IP_ADDRESS" IS '관리자 접속 IP';

CREATE TABLE "COMPETITION_ALLOWED_STOCKS" (
    "ID" NUMBER (19) NOT NULL,
    "COMPETITION_ID" NUMBER (19) NOT NULL,
    "STOCK_ID" NUMBER (19) NOT NULL
);

COMMENT ON COLUMN "COMPETITION_ALLOWED_STOCKS"."STOCK_ID" IS '대회 내 매매 허용 종목. 미등록 시 전 종목 허용';

CREATE TABLE "USER_ACTIVITY_LOGS" (
    "ID" NUMBER (19) NOT NULL,
    "USER_ID" NUMBER (19) NOT NULL,
    "ACTION_TYPE" VARCHAR2 (30) NOT NULL,
    "DETAIL" VARCHAR2 (500) NULL,
    "IP_ADDRESS" VARCHAR2 (45) NULL,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================================
-- 2. PRIMARY KEY 제약조건
-- ============================================================

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("ID");

ALTER TABLE "STOCKS" ADD CONSTRAINT "PK_STOCKS" PRIMARY KEY ("ID");

ALTER TABLE "COMPETITIONS"
ADD CONSTRAINT "PK_COMPETITIONS" PRIMARY KEY ("ID");

ALTER TABLE "ACCOUNTS"
ADD CONSTRAINT "PK_ACCOUNTS" PRIMARY KEY ("ID");

ALTER TABLE "WATCHLIST_GROUPS"
ADD CONSTRAINT "PK_WATCHLIST_GROUPS" PRIMARY KEY ("ID");

ALTER TABLE "POSTS" ADD CONSTRAINT "PK_POSTS" PRIMARY KEY ("ID");

ALTER TABLE "PROFILE_SETTINGS"
ADD CONSTRAINT "PK_PROFILE_SETTINGS" PRIMARY KEY ("ID");

ALTER TABLE "CHAT_MESSAGES"
ADD CONSTRAINT "PK_CHAT_MESSAGES" PRIMARY KEY ("ID");

ALTER TABLE "INQUIRIES"
ADD CONSTRAINT "PK_INQUIRIES" PRIMARY KEY ("ID");

ALTER TABLE "ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("ID");

ALTER TABLE "TRADES" ADD CONSTRAINT "PK_TRADES" PRIMARY KEY ("ID");

ALTER TABLE "COMMENTS"
ADD CONSTRAINT "PK_COMMENTS" PRIMARY KEY ("ID");

ALTER TABLE "PORTFOLIO_SNAPSHOTS"
ADD CONSTRAINT "PK_PORTFOLIO_SNAPSHOTS" PRIMARY KEY ("ID");

ALTER TABLE "PRIZE_HISTORY"
ADD CONSTRAINT "PK_PRIZE_HISTORY" PRIMARY KEY ("ID");

ALTER TABLE "ALERT_SETTINGS"
ADD CONSTRAINT "PK_ALERT_SETTINGS" PRIMARY KEY ("ID");

ALTER TABLE "COMPETITION_PARTICIPANTS"
ADD CONSTRAINT "PK_COMPETITION_PARTICIPANTS" PRIMARY KEY ("ID");

ALTER TABLE "WATCHLIST_FAVORITES"
ADD CONSTRAINT "PK_WATCHLIST_FAVORITES" PRIMARY KEY ("ID");

ALTER TABLE "NOTIFICATIONS"
ADD CONSTRAINT "PK_NOTIFICATIONS" PRIMARY KEY ("ID");

ALTER TABLE "POST_VOTES"
ADD CONSTRAINT "PK_POST_VOTES" PRIMARY KEY ("ID");

ALTER TABLE "OPENBANKING_AUTHS"
ADD CONSTRAINT "PK_OPENBANKING_AUTHS" PRIMARY KEY ("ID");

ALTER TABLE "PRICE_ALERTS"
ADD CONSTRAINT "PK_PRICE_ALERTS" PRIMARY KEY ("ID");

ALTER TABLE "FOLLOWS" ADD CONSTRAINT "PK_FOLLOWS" PRIMARY KEY ("ID");

ALTER TABLE "HOLDINGS"
ADD CONSTRAINT "PK_HOLDINGS" PRIMARY KEY ("ID");

ALTER TABLE "STOCK_ALIASES"
ADD CONSTRAINT "PK_STOCK_ALIASES" PRIMARY KEY ("ID");

ALTER TABLE "REPORTS" ADD CONSTRAINT "PK_REPORTS" PRIMARY KEY ("ID");

ALTER TABLE "ANNOUNCEMENTS"
ADD CONSTRAINT "PK_ANNOUNCEMENTS" PRIMARY KEY ("ID");

ALTER TABLE "SYSTEM_NOTICES"
ADD CONSTRAINT "PK_SYSTEM_NOTICES" PRIMARY KEY ("ID");

ALTER TABLE "ADMIN_ACTION_LOGS"
ADD CONSTRAINT "PK_ADMIN_ACTION_LOGS" PRIMARY KEY ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "PK_COMPETITION_ALLOWED_STOCKS" PRIMARY KEY ("ID");

ALTER TABLE "USER_ACTIVITY_LOGS"
ADD CONSTRAINT "PK_USER_ACTIVITY_LOGS" PRIMARY KEY ("ID");

-- ============================================================
-- 2-1. UNIQUE 제약조건
-- ============================================================

ALTER TABLE "USERS" ADD CONSTRAINT "UK_USERS_EMAIL" UNIQUE ("EMAIL");

ALTER TABLE "USERS"
ADD CONSTRAINT "UK_USERS_NICKNAME" UNIQUE ("NICKNAME");

ALTER TABLE "STOCKS" ADD CONSTRAINT "UK_STOCKS_CODE" UNIQUE ("CODE");

ALTER TABLE "PROFILE_SETTINGS"
ADD CONSTRAINT "UK_PROFILE_SETTINGS_USER" UNIQUE ("USER_ID");

ALTER TABLE "ALERT_SETTINGS"
ADD CONSTRAINT "UK_ALERT_SETTINGS_USER" UNIQUE ("USER_ID");

ALTER TABLE "FOLLOWS"
ADD CONSTRAINT "UK_FOLLOWS_PAIR" UNIQUE ("FOLLOWER_ID", "FOLLOWING_ID");

-- ============================================================
-- 3. FOREIGN KEY 제약조건
-- (REPORTS.TARGET_ID 는 다형성 참조라 FK 미설정)
-- ============================================================

ALTER TABLE "ACCOUNTS"
ADD CONSTRAINT "FK_ACCOUNTS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "ACCOUNTS"
ADD CONSTRAINT "FK_ACCOUNTS_COMPETITION" FOREIGN KEY ("COMPETITION_ID") REFERENCES "COMPETITIONS" ("ID");

ALTER TABLE "COMPETITIONS"
ADD CONSTRAINT "FK_COMPETITIONS_CREATOR" FOREIGN KEY ("CREATED_BY") REFERENCES "USERS" ("ID");

ALTER TABLE "WATCHLIST_GROUPS"
ADD CONSTRAINT "FK_WATCHLIST_GROUPS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "PROFILE_SETTINGS"
ADD CONSTRAINT "FK_PROFILE_SETTINGS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "CHAT_MESSAGES"
ADD CONSTRAINT "FK_CHAT_MESSAGES_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "INQUIRIES"
ADD CONSTRAINT "FK_INQUIRIES_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "ORDERS"
ADD CONSTRAINT "FK_ORDERS_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID");

ALTER TABLE "ORDERS"
ADD CONSTRAINT "FK_ORDERS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "TRADES"
ADD CONSTRAINT "FK_TRADES_ORDER" FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS" ("ID");

ALTER TABLE "TRADES"
ADD CONSTRAINT "FK_TRADES_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID");

ALTER TABLE "TRADES"
ADD CONSTRAINT "FK_TRADES_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "COMMENTS"
ADD CONSTRAINT "FK_COMMENTS_POST" FOREIGN KEY ("POST_ID") REFERENCES "POSTS" ("ID");

ALTER TABLE "COMMENTS"
ADD CONSTRAINT "FK_COMMENTS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "COMMENTS"
ADD CONSTRAINT "FK_COMMENTS_PARENT" FOREIGN KEY ("PARENT_ID") REFERENCES "COMMENTS" ("ID");

ALTER TABLE "POSTS"
ADD CONSTRAINT "FK_POSTS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "POSTS"
ADD CONSTRAINT "FK_POSTS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "PORTFOLIO_SNAPSHOTS"
ADD CONSTRAINT "FK_PORTFOLIO_SNAPSHOTS_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID");

ALTER TABLE "PRIZE_HISTORY"
ADD CONSTRAINT "FK_PRIZE_HISTORY_COMPETITION" FOREIGN KEY ("COMPETITION_ID") REFERENCES "COMPETITIONS" ("ID");

ALTER TABLE "PRIZE_HISTORY"
ADD CONSTRAINT "FK_PRIZE_HISTORY_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "PRIZE_HISTORY"
ADD CONSTRAINT "FK_PRIZE_HISTORY_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID");

ALTER TABLE "ALERT_SETTINGS"
ADD CONSTRAINT "FK_ALERT_SETTINGS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "COMPETITION_PARTICIPANTS"
ADD CONSTRAINT "FK_COMP_PART_COMPETITION" FOREIGN KEY ("COMPETITION_ID") REFERENCES "COMPETITIONS" ("ID");

ALTER TABLE "COMPETITION_PARTICIPANTS"
ADD CONSTRAINT "FK_COMP_PART_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "COMPETITION_PARTICIPANTS"
ADD CONSTRAINT "FK_COMP_PART_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID");

ALTER TABLE "WATCHLIST_FAVORITES"
ADD CONSTRAINT "FK_WATCHLIST_FAVORITES_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "WATCHLIST_FAVORITES"
ADD CONSTRAINT "FK_WATCHLIST_FAVORITES_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "WATCHLIST_FAVORITES"
ADD CONSTRAINT "FK_WATCHLIST_FAVORITES_GROUP" FOREIGN KEY ("GROUP_ID") REFERENCES "WATCHLIST_GROUPS" ("ID");

ALTER TABLE "NOTIFICATIONS"
ADD CONSTRAINT "FK_NOTIFICATIONS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "POST_VOTES"
ADD CONSTRAINT "FK_POST_VOTES_POST" FOREIGN KEY ("POST_ID") REFERENCES "POSTS" ("ID");

ALTER TABLE "POST_VOTES"
ADD CONSTRAINT "FK_POST_VOTES_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "OPENBANKING_AUTHS"
ADD CONSTRAINT "FK_OPENBANKING_AUTHS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "PRICE_ALERTS"
ADD CONSTRAINT "FK_PRICE_ALERTS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "PRICE_ALERTS"
ADD CONSTRAINT "FK_PRICE_ALERTS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "FOLLOWS"
ADD CONSTRAINT "FK_FOLLOWS_FOLLOWER" FOREIGN KEY ("FOLLOWER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "FOLLOWS"
ADD CONSTRAINT "FK_FOLLOWS_FOLLOWING" FOREIGN KEY ("FOLLOWING_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "HOLDINGS"
ADD CONSTRAINT "FK_HOLDINGS_ACCOUNT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNTS" ("ID");

ALTER TABLE "HOLDINGS"
ADD CONSTRAINT "FK_HOLDINGS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "STOCK_ALIASES"
ADD CONSTRAINT "FK_STOCK_ALIASES_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "REPORTS"
ADD CONSTRAINT "FK_REPORTS_REPORTER" FOREIGN KEY ("REPORTER_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "ADMIN_ACTION_LOGS"
ADD CONSTRAINT "FK_AAL_ADMIN" FOREIGN KEY ("ADMIN_ID") REFERENCES "USERS" ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "FK_CAS_COMPETITION" FOREIGN KEY ("COMPETITION_ID") REFERENCES "COMPETITIONS" ("ID");

ALTER TABLE "COMPETITION_ALLOWED_STOCKS"
ADD CONSTRAINT "FK_CAS_STOCK" FOREIGN KEY ("STOCK_ID") REFERENCES "STOCKS" ("ID");

ALTER TABLE "USER_ACTIVITY_LOGS"
ADD CONSTRAINT "FK_USER_ACTIVITY_LOGS_USER" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("ID");

-- ============================================================
-- 4. SEQUENCE 생성 (JPA @SequenceGenerator allocationSize=50과 매칭)
-- ============================================================

CREATE SEQUENCE "USERS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "STOCKS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "COMPETITIONS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "ACCOUNTS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "WATCHLIST_GROUPS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "POSTS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "PROFILE_SETTINGS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "CHAT_MESSAGES_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "INQUIRIES_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "ORDERS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "TRADES_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "COMMENTS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "PORTFOLIO_SNAPSHOTS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "PRIZE_HISTORY_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "ALERT_SETTINGS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "COMPETITION_PARTICIPANTS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "WATCHLIST_FAVORITES_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "NOTIFICATIONS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "POST_VOTES_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "OPENBANKING_AUTHS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "PRICE_ALERTS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "FOLLOWS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "HOLDINGS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "STOCK_ALIASES_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "REPORTS_SEQ" START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "ANNOUNCEMENTS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "SYSTEM_NOTICES_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "ADMIN_ACTION_LOGS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "COMPETITION_ALLOWED_STOCKS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

CREATE SEQUENCE "USER_ACTIVITY_LOGS_SEQ" START
WITH
    1 INCREMENT BY 50 NOCACHE;

-- ============================================================
-- 5. 검증용 확인 쿼리 (실행 후 참고용, 아래는 주석)
-- ============================================================
-- SELECT COUNT(*) FROM USER_TABLES;      -- 30개 나와야 정상
-- SELECT COUNT(*) FROM USER_SEQUENCES;   -- 30개 나와야 정상
-- SELECT COUNT(*) FROM USER_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'R'; -- FK 개수 확인